Add check in docs build artifacts

diff --git a/.github/workflows/any_changes.yaml b/.github/workflows/any_changes.yaml
--- a/.github/workflows/any_changes.yaml
+++ b/.github/workflows/any_changes.yaml
@@ -26,3 +26,13 @@ jobs:
           run: make documentation
           env:
             HUGGING_FACE_TOKEN: ${{ secrets.HUGGING_FACE_TOKEN }}
+
+        - name: Check documentation build
+          run: |
+            for notebook in $(find docs/_build/jupyter_execute -name "*.ipynb"); do
+              if grep -q '"output_type": "error"' "$notebook"; then
+                echo "Error found in $notebook"
+                cat "$notebook"
+                exit 1
+              fi
+            done
